EIP1-4186: EIP1:4352: API spec for updating AED status
cabinetoffice/eip-ero-print-api pull request #182
Opened 2023-03-06 12:59 UTC by vishalgupta-valtech

<img width="920" alt="image" src="https://user-images.githubusercontent.com/73763010/223117115-8af62b1e-1bad-47f9-a33f-6899c3d93833.png">

**Updated to use `certificateNumber`** 
<img width="924" alt="image" src="https://user-images.githubusercontent.com/73763010/223460219-9c856e02-1688-4b55-a485-664571eab327.png">

2023-03-06 16:22 UTC, Neil-Massey commented on src/main/resources/openapi/PrintAPIs.yaml
> +      - name: documentNumber
Is this the same as the `certificate_number` in the database?

2023-03-06 16:33 UTC, sentioservices approved these changes
LGTM

2023-03-06 17:26 UTC, matt-wills-valtech requested changes
I don't think we should make a partial change to switch to `documentNumber` before we're received confirmation.

In the meantime, we could opt for `certificateNumber` and change it everywhere in the print-api if the need arises (not least because it may take a while to get a decision!), but let's decide tomorrow 👍

2023-03-07 14:59 UTC, vishalgupta-valtech commented
> Robin has confirmed we should stick with certificate number:
> 
> ![image](https://user-images.githubusercontent.com/107410075/223411252-4e73d888-24ae-4f74-b349-e26e5625961b.png)



> Robin has confirmed we should stick with certificate number:
> 
> ![image](https://user-images.githubusercontent.com/107410075/223411252-4e73d888-24ae-4f74-b349-e26e5625961b.png)

Thank you @matt-wills-valtech . I have updated the PR and now using a certificateNumber in endpoint url 👍🏼 
<img width="924" alt="image" src="https://user-images.githubusercontent.com/73763010/223460163-7d160342-0937-4fdf-bbc2-801b2c44ccb9.png">

2023-03-07 15:05 UTC, matt-wills-valtech approved these changes
LGTM

2023-03-07 15:56 UTC, merged

2023-03-07 20:37 UTC, vishalgupta-valtech commented
Follow up PR that corrects a little typo https://github.com/cabinetoffice/eip-ero-print-api/pull/183